# Generated by Django 5.0.6 on 2024-09-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="post",
            field=models.ManyToManyField(related_name="tags", to="blog.post"),
        ),
    ]
