# Generated by Django 5.0.6 on 2024-08-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can add a book'), ('can_change_book', 'can change a book'), ('can_delete_book', 'can delete a book')]},
        ),
    ]
